apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-bp
  namespace: production
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - backend-bp
      - key: env
        operator: In
        values:
          - staging
  template:
    metadata:
      labels:
        app: backend-bp
        env: staging
    spec:
      containers:
      - name: backend-bp
        image: fajarsujai/bpbe:latest
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-bp-service
spec:
  type: NodePort
  selector:
    app: backend-bp
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP

