apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: amazonEBS
spec:
  storageClassName: gp2
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0f5df909fcb0d57bd
    fsType: ext4