apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bp
  namespace: staging
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend-bp
      - key: env
        operator: In
        values:
          - staging
  replicas: 3
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: frontend-bp
        env: staging
    spec:
      containers:
      - name: frontend-bp
        image: fajarsujai/bpfe:latest
        env:
          - name: REACT_APP_BASE_URL
            value: "https://be-prod.fajarsujai.my.id"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      #   volumeMounts:
      #     - name: pv-fe-storage3
      #       mountPath: /var/www/html
      # volumes:
      #   - name: pv-fe-storage3
      #     persistentVolumeClaim:
      #       claimName: pvc-fe3
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-bp-service-staging
  namespace: staging
spec:
  type: NodePort
  selector:
    app: frontend-bp
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend-bp
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-bp
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70