apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-bp
  namespace: production
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - backend-bp
      - key: env
        operator: In
        values:
          - staging
  template:
    metadata:
      labels:
        app: backend-bp
        env: staging
    spec:
      containers:
      - name: backend-bp
        image: fajarsujai/bpbe:latest
        env:
          - name: MONGO_SVC_BASE_URL
            value: "backend-bp-service-prod"
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-bp-service-prod
spec:
  type: NodePort
  selector:
    app: backend-bp
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend-bp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-bp
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

